### ISSUE TITLE
Create todo list 

### ISSUE THREAD

**Issue by carlosbuitragosan** [fac28/todo-list-nicarlos#7]
- [ ] add new tasks to the list.
 - [ ] mark tasks as complete.
 - [ ] delete tasks from the list.
